[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
touchline_market = "6kZYYdZLJcsU2ZBKKthc7BpddUiYdTbAtGigS2bJc53K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/pulseplay-deploy-authority.json"

[scripts]
test = "pnpm exec tsx tests/touchline-market.ts"
